import type { CEFRLevel } from "./data/types";

export interface RoleplayScenario {
  id: string;
  level: CEFRLevel;
  title: string;
  titleDe: string;
  emoji: string;
  category: string;
  scenario: string;
  persona: string;
  personaDescription: string;
  openingLine: string;
  openingLineEn: string;
  setting: string;
  goals: string[];
  usefulPhrases: { de: string; en: string }[];
  tags: string[];
}

export const ROLEPLAY_SCENARIOS: RoleplayScenario[] = [
  { id: "rp-a1-1", level: "A1", title: "Meeting Someone New", titleDe: "Jemanden kennenlernen", emoji: "👋", category: "Social", scenario: "You're at a language school in Berlin. A friendly classmate approaches you.", persona: "Anna, a friendly German student", personaDescription: "Anna is 25, studies in Berlin, and is curious about you.", openingLine: "Hallo! Ich bin Anna. Wie heißt du?", openingLineEn: "Hello! I'm Anna. What's your name?", setting: "Language school in Berlin", goals: ["Introduce yourself", "Say where you're from", "Ask Anna a question"], usefulPhrases: [{ de: "Ich heiße...", en: "My name is..." }, { de: "Ich komme aus...", en: "I come from..." }, { de: "Wo wohnst du?", en: "Where do you live?" }], tags: ["introductions", "social"] },
  { id: "rp-a1-2", level: "A1", title: "Ordering at a Café", titleDe: "Im Café bestellen", emoji: "☕", category: "Daily Life", scenario: "You're at a German café. The waiter comes to take your order.", persona: "Thomas, a friendly café waiter", personaDescription: "Thomas is polite and patient.", openingLine: "Guten Tag! Was darf ich Ihnen bringen?", openingLineEn: "Good day! What can I get for you?", setting: "A café in Munich", goals: ["Order a drink", "Order something to eat", "Ask for the bill"], usefulPhrases: [{ de: "Ich hätte gern...", en: "I would like..." }, { de: "Die Rechnung, bitte.", en: "The bill, please." }, { de: "Was kostet das?", en: "How much does it cost?" }], tags: ["food", "cafe"] },
  { id: "rp-a1-3", level: "A1", title: "Asking for Directions", titleDe: "Nach dem Weg fragen", emoji: "🗺️", category: "Travel", scenario: "You're lost in Berlin and need to find the train station.", persona: "Markus, a helpful Berliner", personaDescription: "Markus is friendly and gives clear directions.", openingLine: "Ja, kann ich Ihnen helfen?", openingLineEn: "Yes, can I help you?", setting: "A street in Berlin", goals: ["Ask where the station is", "Understand the directions", "Ask how far it is"], usefulPhrases: [{ de: "Wo ist der Bahnhof?", en: "Where is the station?" }, { de: "Wie weit ist es?", en: "How far is it?" }, { de: "Können Sie das wiederholen?", en: "Can you repeat that?" }], tags: ["travel", "directions"] },
  { id: "rp-a1-4", level: "A1", title: "At the Bakery", titleDe: "In der Bäckerei", emoji: "🥖", category: "Daily Life", scenario: "You're at a German bakery. The baker greets you.", persona: "Frau Müller, a friendly baker", personaDescription: "Frau Müller is warm and cheerful.", openingLine: "Guten Morgen! Was darf es sein?", openingLineEn: "Good morning! What would you like?", setting: "A bakery", goals: ["Ask for bread", "Ask the price", "Say thank you"], usefulPhrases: [{ de: "Zwei Brötchen, bitte.", en: "Two rolls, please." }, { de: "Was kostet das?", en: "How much does it cost?" }, { de: "Vielen Dank!", en: "Thank you very much!" }], tags: ["food", "shopping"] },
  { id: "rp-a2-1", level: "A2", title: "Doctor's Visit", titleDe: "Beim Arzt", emoji: "🩺", category: "Health", scenario: "You're at a doctor's office in Germany.", persona: "Dr. Schmidt, a caring doctor", personaDescription: "Dr. Schmidt is thorough and patient.", openingLine: "Guten Tag! Was fehlt Ihnen?", openingLineEn: "Good day! What's wrong?", setting: "A doctor's office", goals: ["Describe your symptoms", "Say how long you've had them", "Ask about medication"], usefulPhrases: [{ de: "Ich habe Kopfschmerzen.", en: "I have a headache." }, { de: "Seit drei Tagen.", en: "For three days." }, { de: "Was soll ich nehmen?", en: "What should I take?" }], tags: ["health", "doctor"] },
  { id: "rp-a2-2", level: "A2", title: "Apartment Viewing", titleDe: "Wohnungsbesichtigung", emoji: "🏠", category: "Daily Life", scenario: "You're viewing an apartment to rent.", persona: "Herr Wagner, the landlord", personaDescription: "Herr Wagner is business-like but friendly.", openingLine: "Willkommen! Kommen Sie rein.", openingLineEn: "Welcome! Come in.", setting: "An apartment for rent", goals: ["Ask about the rent", "Say what you do", "Ask when you can move in"], usefulPhrases: [{ de: "Wie hoch ist die Miete?", en: "How much is the rent?" }, { de: "Ist eine Küche vorhanden?", en: "Is there a kitchen?" }, { de: "Wann kann ich einziehen?", en: "When can I move in?" }], tags: ["home", "housing"] },
  { id: "rp-a2-3", level: "A2", title: "Shopping for Clothes", titleDe: "Kleidung einkaufen", emoji: "👕", category: "Shopping", scenario: "You're at a clothing store looking for a jacket.", persona: "Lisa, a helpful shop assistant", personaDescription: "Lisa is fashionable and attentive.", openingLine: "Kann ich Ihnen helfen?", openingLineEn: "Can I help you?", setting: "A clothing store", goals: ["Say what you're looking for", "Ask for a different size", "Ask about the price"], usefulPhrases: [{ de: "Ich suche eine Jacke.", en: "I'm looking for a jacket." }, { de: "Haben Sie das in Größe M?", en: "Do you have this in size M?" }, { de: "Kann ich das anprobieren?", en: "Can I try this on?" }], tags: ["shopping", "clothing"] },
  { id: "rp-a2-4", level: "A2", title: "Making Weekend Plans", titleDe: "Wochenendpläne", emoji: "📅", category: "Social", scenario: "You're talking with a friend about weekend plans.", persona: "Julia, your German friend", personaDescription: "Julia is fun and has lots of ideas.", openingLine: "Hallo! Was machst du am Wochenende?", openingLineEn: "Hi! What are you doing this weekend?", setting: "A phone call", goals: ["Talk about what you'd like to do", "Suggest a time to meet", "Make a plan"], usefulPhrases: [{ de: "Wollen wir uns treffen?", en: "Shall we meet?" }, { de: "Wann und wo?", en: "When and where?" }, { de: "Das ist eine gute Idee!", en: "That's a good idea!" }], tags: ["social", "planning"] },
  { id: "rp-b1-1", level: "B1", title: "Job Interview", titleDe: "Bewerbungsgespräch", emoji: "💼", category: "Work", scenario: "You're in a job interview at a German company.", persona: "Frau Dr. Hoffmann, HR Director", personaDescription: "Professional and asks probing questions.", openingLine: "Guten Tag. Erzählen Sie etwas über sich.", openingLineEn: "Good day. Tell me about yourself.", setting: "A corporate office", goals: ["Describe your experience", "Explain why you want this job", "Ask a question about the company"], usefulPhrases: [{ de: "Ich habe fünf Jahre Erfahrung...", en: "I have five years of experience..." }, { de: "Meine Stärken sind...", en: "My strengths are..." }, { de: "Ich bin teamfähig.", en: "I'm a team player." }], tags: ["work", "interview"] },
  { id: "rp-b1-2", level: "B1", title: "Discussing a Movie", titleDe: "Über einen Film diskutieren", emoji: "🎬", category: "Social", scenario: "You just watched a German film with a friend.", persona: "Felix, your film-loving friend", personaDescription: "Felix is opinionated about cinema.", openingLine: "Also, was hast du von dem Film gehalten?", openingLineEn: "So, what did you think of the film?", setting: "After a movie at a café", goals: ["Express your opinion", "Talk about the acting", "Agree or disagree"], usefulPhrases: [{ de: "Meiner Meinung nach...", en: "In my opinion..." }, { de: "Ich fand die Geschichte spannend.", en: "I found the story exciting." }, { de: "Das stimmt, aber...", en: "That's true, but..." }], tags: ["social", "media"] },
  { id: "rp-b1-3", level: "B1", title: "At the Pharmacy", titleDe: "In der Apotheke", emoji: "💊", category: "Health", scenario: "You need medicine at a German pharmacy.", persona: "Frau Klein, a knowledgeable pharmacist", personaDescription: "Helpful and thorough.", openingLine: "Guten Tag! Was kann ich für Sie tun?", openingLineEn: "Good day! What can I do for you?", setting: "A pharmacy", goals: ["Describe your symptoms", "Ask about side effects", "Ask how often to take medicine"], usefulPhrases: [{ de: "Ich brauche etwas gegen...", en: "I need something for..." }, { de: "Haben Sie Nebenwirkungen?", en: "Does it have side effects?" }, { de: "Wie oft soll ich es nehmen?", en: "How often should I take it?" }], tags: ["health", "pharmacy"] },
  { id: "rp-b1-4", level: "B1", title: "Talking About Your Trip", titleDe: "Über eine Reise sprechen", emoji: "✈️", category: "Travel", scenario: "You just returned from a trip. A colleague asks about it.", persona: "Sandra, a curious colleague", personaDescription: "Interested in travel and asks detailed questions.", openingLine: "Willkommen zurück! Wie war deine Reise?", openingLineEn: "Welcome back! How was your trip?", setting: "Office kitchen", goals: ["Describe what you did", "Talk about places visited", "Share a memorable experience"], usefulPhrases: [{ de: "Die Reise war wunderbar.", en: "The trip was wonderful." }, { de: "Ich war in Berlin und München.", en: "I was in Berlin and Munich." }, { de: "Am interessantesten war...", en: "The most interesting thing was..." }], tags: ["travel", "experience"] },
  { id: "rp-b2-1", level: "B2", title: "Debating Climate Policy", titleDe: "Klimapolitik debattieren", emoji: "🌍", category: "Politics", scenario: "You're at a dinner party discussing climate change.", persona: "Prof. Weber, an environmental scientist", personaDescription: "Passionate about climate action.", openingLine: "Ich finde, die Regierung tut nicht genug. Was denken Sie?", openingLineEn: "I think the government isn't doing enough. What do you think?", setting: "A dinner party", goals: ["Express a nuanced opinion", "Argue for specific measures", "Acknowledge counterarguments"], usefulPhrases: [{ de: "Meiner Ansicht nach müssten wir...", en: "In my view we should..." }, { de: "Andererseits muss man bedenken...", en: "On the other hand..." }, { de: "Ich sehe das anders.", en: "I see it differently." }], tags: ["politics", "debate"] },
  { id: "rp-b2-2", level: "B2", title: "Negotiating a Contract", titleDe: "Vertrag verhandeln", emoji: "📝", category: "Work", scenario: "You're negotiating a business contract.", persona: "Herr Becker, a senior partner", personaDescription: "Shrewd but fair.", openingLine: "Danke für Ihr Angebot. Ich möchte einige Punkte besprechen.", openingLineEn: "Thank you for your offer. I'd like to discuss some points.", setting: "A business meeting", goals: ["Defend your position", "Propose a compromise", "Use formal language"], usefulPhrases: [{ de: "Wir müssen darauf bestehen...", en: "We must insist..." }, { de: "Ich schlage folgenden Kompromiss vor.", en: "I propose a compromise." }, { de: "Das ist für uns nicht akzeptabel.", en: "That's not acceptable for us." }], tags: ["business", "negotiation"] },
  { id: "rp-b2-3", level: "B2", title: "Discussing AI Ethics", titleDe: "KI-Ethik diskutieren", emoji: "🤖", category: "Technology", scenario: "You're at a tech meetup discussing AI ethics.", persona: "Dr. Lena Fischer, an AI researcher", personaDescription: "Analytical and asks probing questions.", openingLine: "Finden Sie nicht, dass KI die Gesellschaft verändern wird?", openingLineEn: "Don't you think AI will change society?", setting: "A tech meetup in Berlin", goals: ["Express a sophisticated opinion", "Discuss ethical implications", "Engage in intellectual debate"], usefulPhrases: [{ de: "Das wirft die Frage auf...", en: "That raises the question..." }, { de: "Man muss unterscheiden...", en: "One must distinguish..." }, { de: "Ich würde argumentieren...", en: "I would argue..." }], tags: ["technology", "debate"] },
  { id: "rp-b2-4", level: "B2", title: "Cultural Differences", titleDe: "Kulturdiskussion", emoji: "🌐", category: "Social", scenario: "You're at an international dinner discussing cultural differences.", persona: "Yuki, an exchange student from Japan", personaDescription: "Thoughtful and curious.", openingLine: "Mir ist aufgefallen, dass die Deutschen sehr direkt sind. Wie ist das bei Ihnen?", openingLineEn: "I noticed Germans are very direct. How is it in your culture?", setting: "An international dinner", goals: ["Discuss cultural stereotypes", "Share personal experiences", "Compare customs"], usefulPhrases: [{ de: "In meiner Kultur ist es üblich...", en: "In my culture it's customary..." }, { de: "Das ist mir auch aufgefallen.", en: "I noticed that too." }, { de: "Interessanterweise...", en: "Interestingly..." }], tags: ["culture", "discussion"] },
];

export function getScenariosByLevel(level: CEFRLevel): RoleplayScenario[] {
  return ROLEPLAY_SCENARIOS.filter((s) => s.level === level);
}

export function getScenarioById(id: string): RoleplayScenario | undefined {
  return ROLEPLAY_SCENARIOS.find((s) => s.id === id);
}
