"use client";

import { useState, useMemo, useCallback } from "react";
import { useAppStore, type ConversationSession } from "@/lib/store";
import { motion, AnimatePresence } from "framer-motion";
import {
  History,
  MessageSquare,
  Bookmark,
  AlertCircle,
  Calendar,
  Download,
  Trash2,
  ChevronLeft,
  Volume2,
  Sparkles,
  ArrowRight,
  Clock,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { toast } from "sonner";

function formatDate(ts: number): string {
  const d = new Date(ts);
  const now = new Date();
  const isToday = d.toDateString() === now.toDateString();
  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1);
  const isYesterday = d.toDateString() === yesterday.toDateString();

  const time = d.toLocaleTimeString(undefined, { hour: "2-digit", minute: "2-digit" });
  if (isToday) return `Today, ${time}`;
  if (isYesterday) return `Yesterday, ${time}`;
  return d.toLocaleDateString(undefined, { month: "short", day: "numeric", year: d.getFullYear() === now.getFullYear() ? undefined : "numeric" });
}

function formatRelative(ts: number): string {
  const diff = Date.now() - ts;
  const m = Math.floor(diff / 60000);
  if (m < 1) return "just now";
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  const d = Math.floor(h / 24);
  return `${d}d ago`;
}

function buildTranscriptText(session: ConversationSession): string {
  const lines: string[] = [];
  lines.push("Juni Boli Talk — Conversation Transcript");
  lines.push("=".repeat(48));
  lines.push("");
  lines.push(`Title: ${session.title}`);
  if (session.topic) lines.push(`Topic: ${session.topic}`);
  if (session.scenario) lines.push(`Scenario: ${session.scenario}`);
  lines.push(`Level: ${session.level}`);
  lines.push(`Started: ${new Date(session.startedAt).toLocaleString()}`);
  lines.push(`Last activity: ${new Date(session.updatedAt).toLocaleString()}`);
  lines.push(`Messages: ${session.messageCount}`);
  lines.push(`Vocabulary collected: ${session.vocabCollected.length}`);
  lines.push(`Corrections made: ${session.correctionsMade.length}`);
  lines.push("");
  lines.push("-".repeat(48));
  lines.push("");
  lines.push("TRANSCRIPT");
  lines.push("-".repeat(48));
  lines.push("");

  session.messages.forEach((msg, i) => {
    const timestamp = new Date(msg.timestamp).toLocaleTimeString();
    const role = msg.role === "user" ? "YOU" : "TUTOR";
    lines.push(`[${i + 1}] ${role} · ${timestamp}`);
    lines.push(msg.content);
    if (msg.translation) {
      lines.push(`   ↳ Translation: ${msg.translation}`);
    }
    if (msg.corrections && msg.corrections.length > 0) {
      lines.push(`   ↳ Corrections:`);
      msg.corrections.forEach((c) => {
        lines.push(`     • "${c.original}" → "${c.corrected}"`);
        lines.push(`       (${c.explanation})`);
      });
    }
    if (msg.newVocab && msg.newVocab.length > 0) {
      lines.push(`   ↳ New vocabulary:`);
      msg.newVocab.forEach((v) => {
        lines.push(`     • ${v.german} — ${v.english}`);
      });
    }
    if (msg.encouragement) {
      lines.push(`   ↳ ${msg.encouragement}`);
    }
    lines.push("");
  });

  if (session.vocabCollected.length > 0) {
    lines.push("-".repeat(48));
    lines.push("VOCABULARY COLLECTED");
    lines.push("-".repeat(48));
    session.vocabCollected.forEach((v) => {
      lines.push(`• ${v.german} — ${v.english}`);
    });
    lines.push("");
  }

  if (session.correctionsMade.length > 0) {
    lines.push("-".repeat(48));
    lines.push("CORRECTIONS MADE");
    lines.push("-".repeat(48));
    session.correctionsMade.forEach((c, i) => {
      lines.push(`${i + 1}. "${c.original}" → "${c.corrected}"`);
      lines.push(`   ${c.explanation}`);
    });
    lines.push("");
  }

  lines.push("=".repeat(48));
  lines.push("Generated by Juni Boli Talk");
  return lines.join("\n");
}

function downloadTextFile(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function HistoryView() {
  const conversations = useAppStore((s) => s.conversations);
  const deleteConversation = useAppStore((s) => s.deleteConversation);
  const setView = useAppStore((s) => s.setView);

  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [deleteTargetId, setDeleteTargetId] = useState<string | null>(null);

  const sortedConversations = useMemo(
    () => [...conversations].sort((a, b) => b.updatedAt - a.updatedAt),
    [conversations]
  );

  const selected = useMemo(
    () => conversations.find((c) => c.id === selectedId) || null,
    [conversations, selectedId]
  );

  const speak = useCallback((text: string) => {
    if (typeof window === "undefined" || !("speechSynthesis" in window)) return;
    window.speechSynthesis.cancel();
    const u = new SpeechSynthesisUtterance(text);
    u.lang = "de-DE";
    u.rate = 0.92;
    window.speechSynthesis.speak(u);
  }, []);

  const handleExport = useCallback(
    (session: ConversationSession) => {
      const text = buildTranscriptText(session);
      const safeTitle = session.title.replace(/[^a-z0-9-_]+/gi, "-").toLowerCase().slice(0, 40) || "conversation";
      const date = new Date(session.startedAt).toISOString().slice(0, 10);
      downloadTextFile(`linguatalk-${safeTitle}-${date}.txt`, text);
      toast.success("Transcript downloaded");
    },
    []
  );

  const confirmDelete = () => {
    if (!deleteTargetId) return;
    const target = conversations.find((c) => c.id === deleteTargetId);
    deleteConversation(deleteTargetId);
    if (selectedId === deleteTargetId) setSelectedId(null);
    setDeleteTargetId(null);
    if (target) {
      toast.success(`Deleted "${target.title}"`);
    }
  };

  // Empty state
  if (conversations.length === 0) {
    return (
      <div className="px-4 py-8">
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex flex-col items-center text-center max-w-sm mx-auto"
        >
          <div className="w-20 h-20 rounded-3xl bg-gradient-to-br from-violet-100 to-fuchsia-100 dark:from-violet-950/40 dark:to-fuchsia-950/40 flex items-center justify-center mb-4">
            <History className="w-9 h-9 text-violet-600 dark:text-violet-400" />
          </div>
          <h2 className="text-lg font-bold mb-1">No conversations yet</h2>
          <p className="text-sm text-muted-foreground mb-5">
            Your past voice and chat conversations will appear here. Start talking with your AI tutor to see your progress over time.
          </p>
          <Button
            onClick={() => setView("talk")}
            className="rounded-xl bg-accent hover:bg-accent/90"
          >
            <Sparkles className="w-4 h-4 mr-1.5" />
            Start a conversation
          </Button>
        </motion.div>
      </div>
    );
  }

  // Detail view
  if (selected) {
    return (
      <div className="px-4 py-4 space-y-3">
        <button
          onClick={() => setSelectedId(null)}
          className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors"
        >
          <ChevronLeft className="w-4 h-4" />
          Back to history
        </button>

        {/* Conversation header */}
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-card border border-border/60 rounded-2xl p-4"
        >
          <div className="flex items-start justify-between gap-3 mb-3">
            <div className="min-w-0 flex-1">
              <h2 className="text-lg font-bold leading-tight">{selected.title}</h2>
              {selected.topic && (
                <p className="text-xs text-muted-foreground mt-0.5">{selected.topic}</p>
              )}
              <div className="flex items-center gap-1.5 text-[11px] text-muted-foreground mt-1">
                <Calendar className="w-3 h-3" />
                <span>{formatDate(selected.startedAt)}</span>
                <span>·</span>
                <Badge variant="outline" className="text-[9px] h-4 px-1">
                  {selected.level}
                </Badge>
              </div>
            </div>
            <Button
              onClick={() => handleExport(selected)}
              variant="outline"
              size="sm"
              className="rounded-lg flex-shrink-0"
            >
              <Download className="w-3.5 h-3.5 mr-1" />
              Export
            </Button>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-3 gap-2">
            <div className="bg-secondary/40 rounded-lg p-2 text-center">
              <MessageSquare className="w-3.5 h-3.5 mx-auto text-muted-foreground mb-0.5" />
              <div className="text-sm font-bold tabular-nums">{selected.messageCount}</div>
              <div className="text-[9px] uppercase text-muted-foreground">Messages</div>
            </div>
            <div className="bg-secondary/40 rounded-lg p-2 text-center">
              <Bookmark className="w-3.5 h-3.5 mx-auto text-muted-foreground mb-0.5" />
              <div className="text-sm font-bold tabular-nums">{selected.vocabCollected.length}</div>
              <div className="text-[9px] uppercase text-muted-foreground">Vocab</div>
            </div>
            <div className="bg-secondary/40 rounded-lg p-2 text-center">
              <AlertCircle className="w-3.5 h-3.5 mx-auto text-muted-foreground mb-0.5" />
              <div className="text-sm font-bold tabular-nums">{selected.correctionsMade.length}</div>
              <div className="text-[9px] uppercase text-muted-foreground">Fixes</div>
            </div>
          </div>
        </motion.div>

        {/* Transcript */}
        <div className="bg-card border border-border/60 rounded-2xl overflow-hidden">
          <div className="px-4 py-2.5 border-b border-border/40 flex items-center justify-between">
            <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Full Transcript
            </div>
            <div className="text-[10px] text-muted-foreground">
              {selected.messages.length} messages
            </div>
          </div>
          <div className="max-h-[55vh] overflow-y-auto scrollbar-thin p-3 space-y-3">
            <AnimatePresence initial={false}>
              {selected.messages.map((msg, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 6 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: Math.min(i * 0.02, 0.3) }}
                  className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}
                >
                  <div
                    className={`max-w-[85%] rounded-2xl px-3.5 py-2.5 text-sm ${
                      msg.role === "user"
                        ? "bg-primary text-primary-foreground rounded-br-md"
                        : "bg-secondary text-foreground rounded-bl-md"
                    }`}
                  >
                    <div className="flex items-start gap-2">
                      <div className="flex-1 min-w-0">
                        <div className="whitespace-pre-wrap break-words leading-relaxed">
                          {msg.content}
                        </div>
                        {msg.translation && (
                          <div className="mt-1.5 pt-1.5 border-t border-border/30 text-xs opacity-80">
                            {msg.translation}
                          </div>
                        )}
                      </div>
                      {msg.role === "assistant" && (
                        <button
                          onClick={() => speak(msg.content)}
                          className="opacity-80 hover:opacity-100 flex-shrink-0 mt-0.5"
                          title="Listen"
                        >
                          <Volume2 className="w-3.5 h-3.5" />
                        </button>
                      )}
                    </div>

                    {msg.corrections && msg.corrections.length > 0 && (
                      <div className="mt-2 space-y-1 bg-amber-50 dark:bg-amber-950/30 rounded-lg p-2 text-xs">
                        {msg.corrections.map((c, ci) => (
                          <div key={ci} className="text-amber-900 dark:text-amber-200">
                            <div>
                              <span className="line-through opacity-70">{c.original}</span>
                              {" → "}
                              <span className="font-semibold">{c.corrected}</span>
                            </div>
                            <div className="opacity-80 text-[11px] mt-0.5">{c.explanation}</div>
                          </div>
                        ))}
                      </div>
                    )}

                    {msg.newVocab && msg.newVocab.length > 0 && (
                      <div className="mt-2 flex flex-wrap gap-1">
                        {msg.newVocab.map((v, vi) => (
                          <span
                            key={vi}
                            className="inline-flex items-center gap-1 bg-emerald-100/70 dark:bg-emerald-950/40 text-emerald-800 dark:text-emerald-300 rounded-full px-1.5 py-0.5 text-[10px]"
                          >
                            <Bookmark className="w-2.5 h-2.5" />
                            {v.german} — {v.english}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        </div>

        {/* Footer actions */}
        <div className="flex items-center gap-2">
          <Button
            onClick={() => handleExport(selected)}
            variant="outline"
            className="flex-1 rounded-xl"
          >
            <Download className="w-4 h-4 mr-1.5" />
            Download .txt
          </Button>
          <Button
            onClick={() => setView("talk")}
            className="flex-1 rounded-xl bg-accent hover:bg-accent/90"
          >
            <Sparkles className="w-4 h-4 mr-1.5" />
            New chat
          </Button>
        </div>
      </div>
    );
  }

  // List view
  return (
    <div className="px-4 py-4 space-y-4">
      <div className="text-center">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-violet-100 dark:bg-violet-950/30 text-violet-700 dark:text-violet-300 text-xs font-medium mb-2">
          <History className="w-3.5 h-3.5" />
          Conversation History
        </div>
        <h2 className="text-xl font-bold">
          {conversations.length} past {conversations.length === 1 ? "conversation" : "conversations"}
        </h2>
        <p className="text-xs text-muted-foreground mt-1">
          Tap to read the full transcript · Export to share your progress
        </p>
      </div>

      <div className="space-y-2">
        <AnimatePresence initial={false}>
          {sortedConversations.map((conv) => (
            <motion.button
              key={conv.id}
              layout
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, x: -8 }}
              transition={{ duration: 0.18 }}
              onClick={() => setSelectedId(conv.id)}
              className="w-full text-left bg-card border border-border/60 hover:border-border rounded-2xl p-4 transition-all hover:shadow-sm group"
            >
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <h3 className="font-semibold text-sm truncate flex-1">{conv.title}</h3>
                    <Badge variant="outline" className="text-[9px] h-4 px-1 flex-shrink-0">
                      {conv.level}
                    </Badge>
                  </div>
                  {conv.topic && (
                    <p className="text-xs text-muted-foreground truncate">{conv.topic}</p>
                  )}
                  <div className="flex items-center gap-1.5 text-[11px] text-muted-foreground mt-1.5">
                    <Clock className="w-3 h-3" />
                    <span>{formatRelative(conv.updatedAt)}</span>
                  </div>
                </div>
                <ArrowRight className="w-4 h-4 text-muted-foreground opacity-0 group-hover:opacity-100 transition-opacity flex-shrink-0 mt-1" />
              </div>

              <div className="flex items-center gap-3 mt-3">
                <div className="inline-flex items-center gap-1 text-xs text-muted-foreground">
                  <MessageSquare className="w-3 h-3" />
                  <span className="tabular-nums font-medium text-foreground">{conv.messageCount}</span>
                  <span className="opacity-70">msgs</span>
                </div>
                <div className="inline-flex items-center gap-1 text-xs text-muted-foreground">
                  <Bookmark className="w-3 h-3" />
                  <span className="tabular-nums font-medium text-foreground">{conv.vocabCollected.length}</span>
                  <span className="opacity-70">vocab</span>
                </div>
                <div className="inline-flex items-center gap-1 text-xs text-muted-foreground">
                  <AlertCircle className="w-3 h-3" />
                  <span className="tabular-nums font-medium text-foreground">{conv.correctionsMade.length}</span>
                  <span className="opacity-70">fixes</span>
                </div>
              </div>

              <div className="flex items-center gap-2 mt-3 pt-3 border-t border-border/30">
                <span
                  role="button"
                  tabIndex={0}
                  onClick={(e) => {
                    e.stopPropagation();
                    handleExport(conv);
                  }}
                  onKeyDown={(e) => {
                    if (e.key === "Enter" || e.key === " ") {
                      e.stopPropagation();
                      e.preventDefault();
                      handleExport(conv);
                    }
                  }}
                  className="inline-flex items-center gap-1 text-xs font-medium text-muted-foreground hover:text-foreground transition-colors px-2 py-1 rounded-md hover:bg-secondary"
                >
                  <Download className="w-3 h-3" />
                  Export
                </span>
                <span
                  role="button"
                  tabIndex={0}
                  onClick={(e) => {
                    e.stopPropagation();
                    setDeleteTargetId(conv.id);
                  }}
                  onKeyDown={(e) => {
                    if (e.key === "Enter" || e.key === " ") {
                      e.stopPropagation();
                      e.preventDefault();
                      setDeleteTargetId(conv.id);
                    }
                  }}
                  className="inline-flex items-center gap-1 text-xs font-medium text-muted-foreground hover:text-destructive transition-colors px-2 py-1 rounded-md hover:bg-destructive/5"
                >
                  <Trash2 className="w-3 h-3" />
                  Delete
                </span>
              </div>
            </motion.button>
          ))}
        </AnimatePresence>
      </div>

      {/* Delete confirmation */}
      <AlertDialog open={!!deleteTargetId} onOpenChange={(open) => !open && setDeleteTargetId(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete this conversation?</AlertDialogTitle>
            <AlertDialogDescription>
              This will permanently remove the conversation and all its messages, vocabulary, and corrections. This cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={confirmDelete}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              <Trash2 className="w-4 h-4 mr-1.5" />
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
